Data Set

In [2]:
X= [
    [
    [0,1,0],
    [1,1,1],
    [0,1,0],
    ],
    [
    [0,0,0],
    [1,1,1],
    [0,0,0],
    ],
    [
    [1,0,0],
    [0,1,0],
    [0,0,1],
    ],
    [
    [1,1,1],
    [0,0,0],
    [1,1,1],
    ],
    [
    [0,0,1],
    [0,1,0],
    [1,0,0],
    ],
    # [
    # [0,1,0],
    # [1,0,1],
    # [0,1,0],
    # ],
    # [
    # [0,1,0],
    # [1,1,0],
    # [0,1,0],
    # ],
 
]

Y=[
    [1],
    [0],
    [0],
    [0],
    [0],
    # 0,
    # 0,
]

In [3]:
import torch
from torch import tensor
from torch.nn import Linear, Sigmoid, Sequential, MSELoss
from torch.optim import SGD


model = Sequential(
    Linear(9,1),
    Sigmoid(),
   
)

print(model)


Sequential(
  (0): Linear(in_features=9, out_features=1, bias=True)
  (1): Sigmoid()
)


In [4]:
def reshapeMatrix(x_3x3):
    x_1x9=[]
    for ri in range(3):
       for ci in range(3):
           x_1x9.append(x_3x3[ri][ci])
    return x_1x9

In [5]:
x = tensor(reshapeMatrix(X[1]), dtype = torch.float)
print(x)

tensor([0., 0., 0., 1., 1., 1., 0., 0., 0.])


In [6]:
criterion = MSELoss()     ##loss
optimizer = SGD(model.parameters(), lr = 0.1)



In [7]:
## trening
for epoch in range(2000):
    for i in range(len(X)):
        avg_loss=0
        
        ## pick up data > tensor
        x = tensor(reshapeMatrix(X[i]), dtype = torch.float)
        y = tensor(Y[i], dtype = torch.float)
        
        ## reset the optimizer  очищается каждый круг
        optimizer.zero_grad()
        
        # predict \forward
        yp = model(x)
        
        # calculate loss
        loss = criterion(y, yp)
        
        # propagate error backward
        loss.backward()
        
        # optimaze \ update
        optimizer.step()
        
        avg_loss += loss.item()  ## tensor > int
    avg_loss /= len(X)
    if epoch % 100 == 0:
        print(f"epoch={epoch:5} loss={avg_loss:12.7f} ")
        

epoch=    0 loss=   0.0522062 
epoch=  100 loss=   0.0003404 
epoch=  200 loss=   0.0000721 
epoch=  300 loss=   0.0000281 
epoch=  400 loss=   0.0000143 
epoch=  500 loss=   0.0000085 
epoch=  600 loss=   0.0000056 
epoch=  700 loss=   0.0000039 
epoch=  800 loss=   0.0000029 
epoch=  900 loss=   0.0000022 
epoch= 1000 loss=   0.0000018 
epoch= 1100 loss=   0.0000014 
epoch= 1200 loss=   0.0000012 
epoch= 1300 loss=   0.0000010 
epoch= 1400 loss=   0.0000008 
epoch= 1500 loss=   0.0000007 
epoch= 1600 loss=   0.0000006 
epoch= 1700 loss=   0.0000005 
epoch= 1800 loss=   0.0000005 
epoch= 1900 loss=   0.0000004 


Neuron Treining



TESTING

In [8]:
for i in range(len(X)):
    
    x = tensor(reshapeMatrix(X[i]), dtype = torch.float)
    yp = model(x)
    
    
    y = 1 if yp> 0.5 else 0

    print(yp, y)
    



tensor([0.9517], grad_fn=<SigmoidBackward0>) 1
tensor([0.0498], grad_fn=<SigmoidBackward0>) 0
tensor([0.0014], grad_fn=<SigmoidBackward0>) 0
tensor([0.0287], grad_fn=<SigmoidBackward0>) 0
tensor([0.0014], grad_fn=<SigmoidBackward0>) 0
